### ISSUE TITLE
exception will occur without permission

### ISSUE THREAD

**Issue by s2quake** [sverrirs/vsgallery#9]
if VsGallery has not permission, exception will occur at DownloadController.cs 44

File.SetLastWriteTime(vsixFilePath, DateTime.Now);

I wonder if you're aware of this. :)

**Comment by sverrirs** [comment]
Hi Choi, thanks for bringing this to my attention :)

When you say "has not permission" you mean that the user that is running the process in IIS doesn't have write privileges to the VSIX Storage directory? Did you manage to fix this issue on your end?

**Comment by s2quake** [comment]
I made it into iis service with an administrator account, but I am not sure why VsGallery directory does not have write privileges. Anyway, I forcibly set write to VsGallery directory to resolve it.

**Comment by sverrirs** [comment]
Thanks for the reply, what did you exactly do to set the write privileges to the vsgallery directory? Through the directory permissions? Which user account did you grant the write privileges to (IIS Manager users)?

Would like to add this to a FAQ at the end of the IIS install guide so all details would be great.

**Comment by s2quake** [comment]
i've simply vsgallery set to allow full control.
